version: 2.1

orbs:
  node: circleci/node@4.7.0  # Using a pre-built orb for Node.js setup
  slack: circleci/slack@4.5.0  # Orb for Slack notifications

# Define parameters
parameters:
  env:
    type: string
    default: "production"
    description: "Environment to deploy (e.g., development, staging, production)"

# Define jobs
jobs:
  build:
    docker:
      - image: cimg/node:14  # Using Docker executor with a Node.js image
    steps:
      - checkout  # Checks out the code from the repository
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm test

  deploy:
    docker:
      - image: cimg/node:14
    parameters:
      env:
        type: string
    steps:
      - checkout
      - run:
          name: Set up environment variables
          command: |
            echo "Deploying to <<parameters.env>> environment"
      - run:
          name: Deploy
          command: |
            if [ "<<parameters.env>>" == "production" ]; then
              echo "Deploying to production..."
            else
              echo "Deploying to non-production environment: <<parameters.env>>"

# Define workflow
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          matrix:
            parameters:
              env: ["development", "staging", "production"]
